### ISSUE TITLE
请问这个shared task 最终有accept论文吗

### ISSUE THREAD

**Issue by ShadowTeamCN** [CLUEbenchmark/LightLM#1]

**Comment by brightmart** [comment]
你搜一下 NLPCC2020 shared task 1, light pre-train model:
Knowledge distillation and data augmentation for NLP light pre-trained
models https://iopscience.iop.org/article/10.1088/1742-6596/1651/1/012043/pdf
https://www.researchgate.net/publication/346115857_Light_Pre-Trained_Chinese_Language_Model_for_NLP_Tasks

**Comment by ShadowTeamCN** [comment]
> 你搜一下 NLPCC2020 shared task 1, light pre-train model:
> Knowledge distillation and data augmentation for NLP light pre-trained
> models https://iopscience.iop.org/article/10.1088/1742-6596/1651/1/012043/pdf
> https://www.researchgate.net/publication/346115857_Light_Pre-Trained_Chinese_Language_Model_for_NLP_Tasks

多谢 ，我去看看
